version: '2'
services:
  php:
    build: Docker/php
    volumes:
      - ./src:/var/www/html
    # environment:
    #    XDEBUG_CONFIG: remote_host=192.168.1.19
  nginx:
    build: Docker/nginx
    links:
        - php
    volumes_from: 
      - php
    ports:
      - 80:80
